Module6 task1
htmlacademy-react/1332021-six-cities-5 pull request #10
Opened 2020-11-09 09:24 UTC by vadimkozin

2020-11-11 07:21 UTC, abeluzhenko requested changes

2020-11-11 07:21 UTC, abeluzhenko commented on src/components/sort/sort.jsx
> +  const [isMenuOpen, toggleMenuOpen] = useState(true);
Не очень корректное имя для сеттера `toggleMenuOpen` - он не переключает флаг, а устанавливает его, это может сильно запутать. Лучше `setIsMenuOpen`

2020-11-11 07:21 UTC, abeluzhenko commented on src/components/sort/sort.jsx
> +    toggleMenuOpen(!isMenuOpen);
Очень опасно так устанавливать стейт внутри обычных колбеков. Это может привести к трудноулавливаемым ошибкам.
В колбеке сейчас есть ссылка на `isMenuOpen`, который создается при каждом новом рендере (при вызове хука). В первый он будет равен дефолтному значение, в остальные разы значению из замыкания, которое создает хук.
Проблема в том, что здесь, в функции, будет создано замыкание именно на тот `isMenuOpen`, который создался выше.
Т.к. стейт не меняется асинхронно, может быть ситуация, когда уже после того как этот колбек создан, мы вызовем toggleMenuOpen, который на следующей итерации event-loop, вызовет ре-рендер. Но если в этот промежуток между вызовом и ререндером сработает данный колбек, то в нем будет использовано старое значение isMenuOpen.
Если это не очень понятно - пиши)
Решения два: 
1. Самое простое использовать другую форму сеттера, такую `toggleMenuOpen(prevState => !prevState)`. Так всегда будет использовано актуальное состояние стейта.
2. Использовать для колбека хук useCallback, указав `isMenuOpen` как зависимость, тогда в замыкании тоже будет актуальное значение.

2020-11-11 07:21 UTC, abeluzhenko commented on src/hocs/with-add-comment/with-add-comment.jsx
> +      ? true : false;
Вроде это можно удалить и ничего не изменится

2020-11-11 07:21 UTC, abeluzhenko commented on src/mocks/offers.js
> +  longitude: coordinates[1],
```suggestion
const getPosition = ([latitude, longitude]) => ({
  latitude,
  longitude,
```

2020-11-11 09:48 UTC, vadimkozin commented on src/components/add-comment/add-comment.jsx
> +    };
Константу вынес на уровень модуля.  И сортировку тоже. А саму идею с объектом Stars оставил. В объекте чётко видно отображение ключей 1..5 на terribly.. perfect. С массивом бы пришлось учитывать то что индексы у него начинаются с нуля. И еще там верстальщик так хитро всё завернул - на экране должно быть слева "всё плохо", а чем правее тем лучше (больше звёзд). А в правилах CSS всё перевёрнуто наоборот, чтобы красиво закрашивать звёзды при наведении.

2020-11-11 09:49 UTC, vadimkozin commented on src/components/sort/sort.jsx
> +    toggleMenuOpen(!isMenuOpen);
А я всё думал где применять useCallback.  И для чего они нужны - и так всё работает. Оказалось вот здесь - самое то.  Сделал вариант 2 - через useCallback.

2020-11-12 06:45 UTC, abeluzhenko approved these changes

2020-11-12 06:45 UTC, merged