Module7 task1
htmlacademy-react/1332021-six-cities-5 pull request #12
Opened 2020-11-14 19:58 UTC by vadimkozin

2020-11-15 19:42 UTC, abeluzhenko requested changes
Все отлично, отправляю на доработку только из-за CITIES_NAME => CITIES_NAMES, т.к. это скорее всего посчитают нарушением критериев. Остальное все не критично, просто FYI

2020-11-15 19:42 UTC, abeluzhenko commented on src/store/api-actions.js
> +    // .then(({data}) => dispatch(loadOffers(data)))
```suggestion
```

2020-11-15 19:42 UTC, abeluzhenko commented on src/store/adapters.js
> +    deleteKeys(adapted, [`type`, `bedrooms`, `goods`, `images`, `preview_image`, `is_favorite`, `is_premium`, `location`, `max_adults`, `host`]);
Мне кажется, лучше сразу брать из оффера только те поля, которые нам нужны, а не удалять здесь лишние. На реальном проекте это была бы очень большая зависимость от бекенда. Плюс, это поможет явно определить интерфейс оффера на клиенте.

2020-11-15 19:42 UTC, abeluzhenko commented on src/store/api-actions.js
> +    })
Думаю, что это можно удалить пока, ничего не изменится. Нет особого смысла ловить ошибку и тут же ее выбрасывать, если промис не в цепочке.

2020-11-15 19:42 UTC, abeluzhenko commented on src/services/api.js
> +      throw err;
Можно удалить, ошибка выбросится дальше

2020-11-15 19:42 UTC, abeluzhenko commented on src/index.js
> +    // window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : (f) => f
Думаю, можно вернуть, в учебном проекте это не проблема.

2020-11-15 19:42 UTC, abeluzhenko commented on src/const.js
> +export const CITIES_NAME = Object.keys(CITIES);
*NAMES, это же массив с именами

2020-11-16 08:55 UTC, vadimkozin commented on src/index.js
> +    // window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : (f) => f
Просто удалил пока. Если вернуть, то пишет: "Uncaught Error: It looks like you are passing several store enhancers to createStore(). This is not supported. Instead, compose them together to a single function."   Ну то есть - "не поддерживается" и нужно обернуть всё в одну функцию. Это как раз в следующем задании(module7-task2) и происходит. А сейчас просто удалил.

2020-11-16 08:55 UTC, vadimkozin commented on src/const.js
> +export const CITIES_NAME = Object.keys(CITIES);
Да. Так и писал вначале CITIES_NAMES. Но усомнился, пошёл в переводчик яндекса и он мне выдал: CITIES NAME --> НАЗВАНИЯ ГОРОДОВ.  А если пишу: "CITIES NAMES" --> "название города".  Поэтому я в коде и написал CITIES_NAME. Короче говоря поправил на CITIES_NAMES, чтобы никого это не смущало.  И посмотрел сейчас гугл-переводчик - он выдаёт : CITIES NAMES --> НАЗВАНИЯ ГОРОДОВ.   Да уж. сколько переводчиков - столько и вариантов.

2020-11-16 14:20 UTC, abeluzhenko approved these changes

2020-11-16 14:20 UTC, merged