Module7 task3
htmlacademy-react/1332021-six-cities-5 pull request #14
Opened 2020-11-23 18:53 UTC by vadimkozin

2020-11-24 09:51 UTC, abeluzhenko requested changes

2020-11-24 09:51 UTC, abeluzhenko commented on src/containers/review-list-container/review-list-container.jsx
> +  React.useEffect(() => {
У эффекта нет зависимости от `offerId`, он не соберет новые комментарии, если `offerId` поменяется. Сейчас такая ситуация невозможна, но если захотим показывать ревью в других условиях, это может выстрелить. Лучше добавить `offerId` в список зависимостей.

2020-11-24 09:51 UTC, abeluzhenko commented on src/containers/room-page-conainer/room-page-container.jsx
> +  }, []);
Здесь тоже не хватает зависимости от `offerId`

2020-11-24 09:51 UTC, abeluzhenko commented on src/containers/room-page-conainer/room-page-container.jsx
> +  }
Этот кусок используется уже 2 раза. Еще 1 и нужно будет завести для этого hoc, который рендерил бы лоадер и ошибку или children-ов в случае успешной загрузки.
Еще, кажется, текст ошибки не совсем корректный.

2020-11-24 09:51 UTC, abeluzhenko commented on src/mocks/reviews.js
> +const uuid2 = getUUIDGenerator();
А зачем добавил еще один генератор? id-шки же уникальные. Учитывая, что это моки, думаю, одного будет достаточно.

2020-11-24 09:51 UTC, abeluzhenko commented on src/store/adapters.js
> +*/
Если уже не нужно, стоит удалить, чтобы потом не поддерживать изменения

2020-11-24 09:51 UTC, abeluzhenko commented on src/store/adapters.js
> +  static adaptToClients(comments) {
Не совсем понял, почему такое имя `adaptToClients`. Вроде смысл в том, что мы адаптируем бекенд-представление к клиентскому, значит множественное число не совсем верное решение.
Плюс, имя класса во множественном числе тоже обычно не очень хорошая идея. Мне кажется будет лучше назвать класс `Comment` и методы `adaptToClient` и `adaptAllToClient/adaptManyToClient`

2020-11-24 09:51 UTC, abeluzhenko commented on src/store/api-config.js
> +export const route = {
Получается немного неконсистетно, что ты в одних случаях используешь классы со статическими методами, а в других глобальные объекты. Результат один и тот же, но стоит выбрать какой-то один поход и его использовать везде.

2020-11-24 09:54 UTC, abeluzhenko commented
Очень понравилось твое решение с фабриками для обработки похожих действий в редюсере, на реальных проектах с redux-tools все это можно значительно упростить: https://redux.js.org/tutorials/fundamentals/part-8-modern-redux#using-createasyncthunk

2020-11-25 16:28 UTC, vadimkozin commented
Всё поправил. Еще добавил логику с /favorite. Проверяй меня пожалуйста быстрее, а то я не успею выйти на защиту. :)

2020-11-25 19:18 UTC, abeluzhenko approved these changes

2020-11-25 19:18 UTC, merged