Module4 task2
htmlacademy-react/1332021-six-cities-5 pull request #7
Opened 2020-10-18 14:24 UTC by vadimkozin

2020-10-19 08:20 UTC, abeluzhenko requested changes

2020-10-19 08:20 UTC, abeluzhenko commented on src/components/map-horizontal/map-horizontal.jsx
> +import React from 'react';
2 компонента, различающиеся только 1 строчкой выглядит как переусложнение. Что, если сделать пропс (например `layoutType`) который бы принимал тип отображения и устанавливал нужный className?

2020-10-19 08:20 UTC, abeluzhenko commented on src/components/map/map.css
> +.map--vertical {
Эти стили объявлены тут, но используются только в декораторе, это не очень удачный дизайн (нарушение инкапсуляции декоратора, нарушения принципа единой ответственности). Правильно будет описать эти стили на уровне декоратора.

2020-10-19 08:20 UTC, abeluzhenko commented on src/components/map/map.jsx
> +    this.addMarkers(map);
Мне кажется, предыдущая версия была более корректной. Всегда лучше явно передавать параметры, чем завязывться на состояние (понятнее, удобнее писать тесты).

2020-10-19 08:20 UTC, abeluzhenko commented on src/components/offer-card/offer-card.jsx
> +  const {onHover, offer, onOfferClick = null, classNameMain, classNameImage, nameBookmark} = props;
А зачем `onOfferClick = null`? Если проп не передать, ок будет `undefined`, этого должно хватить для проверки.

2020-10-19 08:20 UTC, abeluzhenko commented on src/components/offer-list/offer-list.jsx
> +        param = {
Можно сразу делать `return {...}` в каждом кейсе, тогда не нужна будет временная переменная и break-и. Также, хорошим стилем считается всегда добавлять default-кейс (можно возвращать null или пустой объект)

2020-10-19 08:20 UTC, abeluzhenko commented on src/utils.js
> +//                --> 'button active favorite one two yes'
```suggestion
```

2020-10-19 08:20 UTC, abeluzhenko commented on src/utils.js
> +  items.forEach((it) => {
Здесь гораздо логичнее кажется использовать `reduce`, т.к. происходит именно накопление. `forEach`, как правило, используется для сайд-эффектов. Если же нужно вернуть какой-то результат, то лучше использовать другой перебирающий метод.

2020-10-19 11:22 UTC, vadimkozin commented on src/components/map-horizontal/map-horizontal.jsx
> +import React from 'react';
Да, конечно. Ввёл новые (лишние) компоненты MapVertical и MapHorizontal только чтобы соответствовать теме лекции, а лекция была про паттерны. Вот и притянул за уши паттерн "прокси".

2020-10-19 11:29 UTC, vadimkozin commented on src/components/map/map.jsx
> +    this.addMarkers(map);
Вернул как оно было.  Смотрел разный код, и часто видел что  завязываются на состояние/пропсы, а не передают в параметрах. И тут как говориться - если и читать, то только правильную "классическую" литературу.

2020-10-19 11:31 UTC, vadimkozin commented on src/components/offer-card/offer-card.jsx
> +  const {onHover, offer, onOfferClick = null, classNameMain, classNameImage, nameBookmark} = props;
Здесь только подчёркиваю, что параметра может и не быть. Убрал.

2020-10-19 11:34 UTC, vadimkozin commented on src/components/offer-list/offer-list.jsx
> +        param = {
Да, так оно и было. Но default-case не делал, а ESLint всячески намекал, что нужно что-то вернуть из ф-ии. И вот поэтому завёл переменную. Исправил.

2020-10-19 11:35 UTC, vadimkozin commented on src/utils.js
> +  items.forEach((it) => {
Да, логичнее. Переделал на  reduce.

2020-10-20 06:14 UTC, abeluzhenko approved these changes

2020-10-20 06:14 UTC, abeluzhenko commented on src/components/offer-card/offer-card.jsx
> +import {generateClassNames as gcn} from '../../utils';
Имхо, лучше не использовать алиас, `generateClassNames `отличное имя, сразу понятно, что происходит, в отличие от `gcn`

2020-10-20 06:14 UTC, merged